#!/usr/bin/env python3
"""Turn web/page.html into the PAGE_HTML header the firmware serves.

The build runs this for you (see main/CMakeLists.txt), so editing web/page.html
and running `idf.py build` is enough. To do it by hand:

    python3 tools/build_page.py [web/page.html] [out/page.h]
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "web" / "page.html"
OUT = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "main" / "page.h"

html = SRC.read_text()
lines = html.rstrip("\n").splitlines()

body = "\n".join(
    '    "%s\\n"' % line.replace("\\", "\\\\").replace('"', '\\"') for line in lines
)

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "/* Generated from web/page.html by tools/build_page.py - do not edit this file.\n"
    "   Edit web/page.html instead; the build regenerates this header. */\n"
    "#pragma once\n\n"
    "static const char PAGE_HTML[] =\n" + body + ";\n"
)

print("page.h: %s -> %s (%d bytes of html)" % (SRC, OUT, len(html)))
