#!/usr/bin/env python3
"""Turn web/page.html into main/page.h (the PAGE_HTML string the firmware serves).

    python3 tools/build_page.py

The page is plain HTML with the two SVGs inlined, so it can be edited directly.
The header is checked in, so the normal `idf.py build` does not need Python.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "web" / "page.html"
OUT = ROOT / "main" / "page.h"

html = SRC.read_text()
lines = html.rstrip("\n").splitlines()

body = "\n".join(
    '    "%s\\n"' % line.replace("\\", "\\\\").replace('"', '\\"') for line in lines
)

OUT.write_text(
    "/* Generated by tools/build_page.py from web/page.html - do not edit this file.\n"
    "   Edit web/page.html and re-run that script instead. */\n"
    "#pragma once\n\n"
    "static const char PAGE_HTML[] =\n" + body + ";\n"
)

print("wrote %s (%d bytes of html)" % (OUT.relative_to(ROOT), len(html)))
